<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-EarthPurse/blob/main/More_on_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Review

import numpy as np
np.__version__


'2.0.2'

In [ ]:
# explore NumPy
dir(np)[:20] # first 20 entries


['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [ ]:
# get help for a specific function
help(np.sin)


Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [ ]:
#Complete this task

# Find documentation for np.linspace using '?'
np.linspace?




In [ ]:
# Creating vectors
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3


(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

In [ ]:
# Creating matrices
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I


(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [ ]:
# Index and Slicing
A[0, 1], A[:, 0], A[1]


(np.int64(2), array([1, 3]), array([3, 4]))

In [ ]:
# Random matrices
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U


(array([[ 0.66468799, -1.28674447,  0.50507966],
        [ 0.23814455,  1.77825839,  1.62390339],
        [ 0.33334804,  1.28703864,  0.03683694]]),
 array([[0.05476169, 0.98065807, 0.83596161],
        [0.20481178, 0.8481169 , 0.27250867],
        [0.42948349, 0.95256943, 0.95903074]]))

In [ ]:
# Complete this task

# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
# create a 5x5 random matrix
M = np.random.rand(5,5)

# symmetric part
S = 0.5 * (M + M.T)

# antisymmetric part
A = 0.5 * (M - M.T)

M, S, A

# A symmetric matrix A satisfies A = 0.5*(A + A.T);
K = 0.5 * (M - M.T)

# The `.T` attribute finds the transpose of the matrix.
K

array([[ 0.        ,  0.0788892 ,  0.17169232,  0.16041699,  0.0259941 ],
       [-0.0788892 ,  0.        , -0.29027706, -0.01736047, -0.12523609],
       [-0.17169232,  0.29027706,  0.        ,  0.19969853, -0.17083573],
       [-0.16041699,  0.01736047, -0.19969853,  0.        ,  0.27408121],
       [-0.0259941 ,  0.12523609,  0.17083573, -0.27408121,  0.        ]])

In [ ]:
# Elementwise multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

In [ ]:
# Matric multiplication

A @ B

array([[ 70, 100],
       [150, 220]])

In [ ]:
# Function equivalents for matrix multiplication
np.matmul(A, B), np.dot(A, B)


(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [ ]:
# Complete these tasks

# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)

# np.matmul explanation
# Function for matrix multiplication. It operates in linear algebra.
# np.matmul example
np.matmul(A, B)

# np.dot explanation
# Is a sort of generalized dot product function. When its a 1D array, it performs a dot product
# For a 2D array, its matrix multiplication
# np.dot example
np.dot(A, B)

# @ explanation
# Its a matrix multiplication operator.
# @ example
A @ B

# * explanation
# elementwise multiplication
# * example
A * B




array([[ 10,  40],
       [ 90, 160]])

In [ ]:
# Loop version
import math

In [ ]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

269 ms ± 8.16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# Vectorized version
%%timeit
y_vec = np.sin(xs)



NameError: name 'xs' is not defined

In [ ]:
# Complete this task

# ask Gemini about `%%timeit`
# below is what gemini had to say
# The %%timeit magic command is an IPython feature used to measure the execution time of a small block of Python code. It runs the code multiple times (and usually in multiple loops, depending on the execution time) and then reports the average execution time along with its standard deviation. This provides a more reliable measurement than a single execution, especially for very fast operations. It's often used for performance comparison between different implementations of the same task, like in the notebook where it compares a loop-based approach with a vectorized NumPy approach.

In [ ]:
# Complete this task

# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator
def total_energy(m, k, x, v):
    """
    Vectorized total energy of a harmonic oscillator.

    Parameters:
    m : mass
    k : spring constant
    x : position array
    v : velocity array

    Returns:
    Total energy array
    """
    T = 0.7 * m * v**2   # kinetic energy
    U = 0.7 * k * x**2   # potential energy
    return T + U



In [ ]:
# Example matrix
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [ ]:
# Complete this task

# In the above cell, which eigenvector is associated with which eigenvalue?
# - vals[0] corresponds to vecs[:, 0]
# - vals[1] corresponds to vecs[:, 1]
# - vals[2] corresponds to vecs[:, 2]


In [ ]:
# Constructing a stiffness/force-constant matrix
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K


array([[ 2450, -2450],
       [-2450,  2450]])

In [ ]:
# Diagonalize to find frequencies and normal mode displacement patterns

vals, vecs = np.linalg.eigh(K)
vals, vecs


(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [ ]:
# Vibrational frequencies (ignoring mass)
omega = np.sqrt(vals)
omega


array([ 0., 70.])

In [ ]:
# Unitary transformations with eigenvector matrices

# Complete these tasks

# Show that U@U.T and U.T@U are 2x2 identity matrices
# U is the matrix of eigenvectors returned by np.linalg.eigh
U = vecs

# Check orthonormality (unitary transformation)
U @ U.T, U.T @ U



(array([[ 1.00000000e+00, -2.23711432e-17],
        [-2.23711432e-17,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -2.23711432e-17],
        [-2.23711432e-17,  1.00000000e+00]]))

In [ ]:
# Complete this task
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.
# Construct diagonal matrix of eigenvalues
Lambda = np.diag(vals)

# Transform K into the eigenbasis
U.T @ K @ U, Lambda



(array([[ 3.94430453e-31,  6.65719202e-14],
        [-8.69285906e-14,  4.90000000e+03]]),
 array([[   0.,    0.],
        [   0., 4900.]]))

In [ ]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule

# The eigenvector associated with the zero eigenvalue corresponds to the center of mass, where both atoms move together in same direction.
# This mode has zero force or restoring force
# The eigenvector associated with the nonzero eigenvalue corresponds to the stretching mode, where the atoms move in opposite directions.
# This mode represents the vibrational motion of the diatomic molecule.
